name: delta_trace_db
description: "The NoSQL in-memory database with class-based functionality and detailed operation history tracking."
version: 0.1.3
repository: https://github.com/MasahideMori-SimpleAppli/delta_trace_db

environment:
  sdk: ^3.8.1

dependencies:
  file_state_manager: ^3.0.0
  collection: ^1.19.1
  logging: ^1.3.0

dev_dependencies:
  test: ^1.24.0
  lints: ^6.0.0

